version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: diary
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    command: go run main.go
    volumes:
      - ./backend:/app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql_container
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: diary

volumes:
  mysql_data: